-- +goose Up
-- Auto-generated by the server on startup and via a daily background job.
CREATE SEQUENCE IF NOT EXISTS lake.recurring_payment_occurrences_id_seq;
CREATE TABLE IF NOT EXISTS lake.recurring_payment_occurrences (
    id INTEGER NOT NULL DEFAULT nextval('lake.recurring_payment_occurrences_id_seq'),
    recurring_payment_id INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS lake.recurring_payment_occurrences;
DROP SEQUENCE IF EXISTS lake.recurring_payment_occurrences_id_seq;
